
apiVersion: v1
kind: Secret
metadata:
  name: eshopadminserver-gitlabregistryread
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOiB7CiAgICAgICAgICAgICJ1c2VybmFtZSI6IkFLU190ZXN0VGVuYW50X1BvQyIsCiAgICAgICAgICAgICJwYXNzd29yZCI6IlpDZTRTUVpfRjVYRDJ0c3JXODZLIiwKICAgICAgICAgICAgImVtYWlsIjoiIiwKICAgICAgICAgICAgImF1dGgiOiJRVXRUWDNSbGMzUlVaVzVoYm5SZlVHOURPbHBEWlRSVFVWcGZSalZZUkRKMGMzSlhPRFpMIgogICAgICAgIH0KICAgIH0KfQoKCg==
