apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-admin-server
  template:
    metadata:
      labels:
        app: eshop-admin-server
    spec:
      containers:
      - name: eshop-admin-server
        #image: drmaxdevelclusteracr.azurecr.io/drmax_eshop_admin_server:latest
        image: registry.gitlab.com/dr-max/ecom/integrations/drmax-eshop-admin-server:latest
        #resources:
        #  limits:
        #    memory: "512Mi"
        #    cpu: "500m"
        #
        # for testing purposes  
        #command: ["/bin/sh"]
        #args: ["-c", "while true; do echo hello; sleep 10;done"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/usr/src/app/dist/envConfig.json"
          subPath: envConfig.json
          readOnly: true
      imagePullSecrets:
      - name: registry-credentials
        
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "eshopadminmongodbpoc"
