apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: eshopadminmongodbpoc
spec:
  provider: azure
  parameters:
    keyvaultName: "eshopadminmongodbpoc"
    useVMManagedIdentity: "true"
    # AKS -> addonsProfiles ->         
    userAssignedIdentityID: "5cb0adfb-6a32-4485-adc6-808ae530ecb4"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: envconfigjson9
          objectAlias: envConfig.json
          objectType: secret
          objectVersion: ""
    tenantId: "c92d94f7-4cbd-43ea-90bd-33e3013dae06" 