tenant_id               = "c92d94f7-4cbd-43ea-90bd-33e3013dae06"
cluster_name            = "dontDeleteMeManually"
#cluster_name            = "PL-aks-NE-Drmax-ApplAKS001TEST"
cluster_storage_account = "dntdltmmnll"
location                = "North Europe"
kubernetes_version      = "1.20.9"